# Generated by Django 4.2.7 on 2023-11-15 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='publicada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
